apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8081        # Service virtual port
      targetPort: 8080  # container port
      protocol: TCP
  type: ClusterIP
