apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8081        # Service 虛擬連接埠
      targetPort: 8080  # 容器連接埠
      protocol: TCP
  type: ClusterIP
