apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-demo-prod
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - app: backend
                - app: frontend
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{app}}-prod"
      labels:
        app: "{{app}}"
        env: prod
    spec:
      project: default

      source:
        repoURL: https://github.com/KittyChen913/gitops-demo-apps.git
        targetRevision: master
        path: "apps/{{app}}/overlays/prod"

      destination:
        server: '{{server}}'
        namespace: prod

      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
