apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

images:
  - name: gitops-demo-frontend
    newTag: dev

replicas:
  - name: frontend
    count: 1

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: ENV
          value: dev
    target:
      kind: Deployment
      name: frontend
