apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  namespace: argocd
  labels:
    app: frontend
    env: prod
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/gitops-demo-apps.git
    targetRevision: master
    path: apps/frontend/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: prod

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
